version: '3'

services:
  postgres:
    image: postgresql:16.1
    container_name: edauni-cnt
    environment:
      POSTGRES_DB: edauni
      POSTGRES_USER: ulvu
      POSTGRES_PASSWORD: ulvu142536
    volumes:
      - /opt/pg/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      -
  minio:
    container_name: flyjob_auth_dfs
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - config-network