server:
  port: 5000
spring:
  servlet:
    multipart:
      maxFileSize: 25MB
      maxRequestSize: 35MB
  datasource:
    url: jdbc:h2:mem:edauni
    username: root
    password: root
    driverClassName: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      globally_quoted_identifiers: true
      ddlAuto: create-drop
    showSql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: security@edauni.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    elasticsearch:
      host: 35.202.14.93
      port: 9200
      cluster-name: 99d1e62fc3ce
jsa:
  aws:
    accessKeyId: secretkey
    secretAccessKey: accesskey
  s3:
    bucket: edauni
    region: eu-north-1
app:
  jwt:
    title: Bearer
    secretKey: SEkkasdlaijhhsd
    accessTokenSessionTime: 999999999999
    refreshTokenSessionTime: 99999999999
  constants:
    defaultSecurityMail: security@edauni.com
    appName: Edauni
    domain: http://edauni.com
    image-url: https://edauni.s3.eu-north-1.amazonaws.com/
    user:
      default-image: default
      image-folder: public/user/
    blog:
      default-image: default
      image-folder: public/blog/
    file:
      folder: public/file/
    image:
      size-s: thumbS