spring:
  config:
    import: classpath:properties/h2-properties.yml,classpath:properties/s3-properties.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username: edaunicom2@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    elasticsearch:
      host: localhost
      port: 9200
#      cluster-name: 839c66f1568c
minio:
  endpoint: http://localhost:9000
  access-key: minio-root-user
  secret-key: minio-root-password
  bucket-name: edadi
app:
  jwt:
    title: Bearer
    secretKey: KMij3IJWl94kjsOosjaUuIIiiwIo
    accessTokenSessionTime:  864000000
    refreshTokenSessionTime: 5500000000
  constants:
    defaultSecurityMail: edaunicom2@gmail.com
    appName: Edauni
    domain: http://localhost:4200
    image-url: https://edauni.s3.eu-north-1.amazonaws.com/