server:
  port: 5000
spring:
  servlet:
    multipart:
      maxFileSize: 25MB
      maxRequestSize: 35MB
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    datasource:
    username: root
    password: Demo12345
    driverClassName: mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddlAuto: update
      showSql: true
  mail:
    host: dummy.edadi.az
    port: 587
    username: dummy@edadi.az
    password: mypassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jsa:
  aws:
    accessKeyId: secretid
    secretAccessKey: secretkey
  s3:
    bucket: edadiaz/public
    region: region
app:
  jwt:
    title: Bearer
    secretKey: secretkey123
    accessTokenSessionTime: 999999999999
    refreshTokenSessionTime: 99999999999
  constants:
    domain: http://edadi.az
    image-url: https://edadiaz.s3.eu-central-1.amazonaws.com/public
    user:
      default-image: default
      image-folder: /user
    blog:
      default-image: default
      image-folder: /blog
    file:
      folder: /file
    image:
      size-s: thumbS