server:
  port: 5000
spring:
  servlet:
    multipart:
      maxFileSize: 25MB
      maxRequestSize: 35MB
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    showSql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: edaunicom2@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    elasticsearch:
      host: localhost
      port: 9200
minio:
  endpoint: http://localhost:9000
  access-key: minio-root-user
  secret-key: minio-root-password
  bucket-name: edadi
app:
  jwt:
    title: Bearer
    secretKey: assaasdassadasdsad
    accessTokenSessionTime: 999999999999
    refreshTokenSessionTime: 99999999999
  constants:
    defaultSecurityMail: edaunicom2@gmail.com
    appName: Edauni
    domain: http://localhost:4200
    image-url: https://edauni.s3.eu-north-1.amazonaws.com/