server:
  port: 5000
spring:
  servlet:
    multipart:
      maxFileSize: 25MB
      maxRequestSize: 35MB
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
     showSql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: edaunicom2@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    elasticsearch:
      host: localhost
      port: 9200
#      cluster-name: 839c66f1568c
jsa:
  aws:
    accessKeyId: qweq
    secretAccessKey: wqeq
  s3:
    bucket: edauni
    region: eu-north-1
app:
  jwt:
    title: Bearer
    secretKey:
    accessTokenSessionTime: 999999999999
    refreshTokenSessionTime: 99999999999
  constants:
    defaultSecurityMail: edaunicom2@gmail.com
    appName: Edauni
    domain: https://edauni.com
    image-url: https://edauni.s3.eu-north-1.amazonaws.com/
    user:
      default-image: default
      image-folder: public/user/
    blog:
      default-image: default
      image-folder: public/blog/
    file:
      folder: public/file/
    image:
      size-s: thumbS