spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: edaunicom2@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    elasticsearch:
      host: localhost
      port: 9200
#      cluster-name: 839c66f1568c
minio:
  endpoint: http://localhost:9000
  access-key: minio-root-user
  secret-key: minio-root-password
  bucket-name: edadi
app:
  jwt:
    title: Bearer
    secretKey: assaasdassadasdsad
    accessTokenSessionTime: 999999999999
    refreshTokenSessionTime: 99999999999
  constants:
    defaultSecurityMail: edaunicom2@gmail.com
    appName: Edauni
    domain: http://localhost:4200
    image-url: https://edauni.s3.eu-north-1.amazonaws.com/