server:
  port: 5000
spring:
  servlet:
    multipart:
      maxFileSize: 25MB
      maxRequestSize: 35MB
  datasource:
    url: jdbc:mysql://localhost:.3306/demo
    username: edauni
    password: Demo142536
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: hibernate.dialect.MySQL5Dialectorg.
      ddlAuto: update
    showSql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: pass123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jsa:
  aws:
    accessKeyId: keyId
    secretAccessKey: keypas
  s3:
    bucket: edauni/public
    region: eu-north-1
app:
  jwt:
    title: Bearer
    secretKey: secretkey123
    accessTokenSessionTime: 999999999999
    refreshTokenSessionTime: 99999999999
  constants:
    defaultSecurityMail: main@edauni.com
    appName: Edauni
    domain: http://localhost:4200
    image-url: https://edauni.s3.eu-north-1.amazonaws.com/public
    user:
      default-image: default
      image-folder: /user
    blog:
      default-image: default
      image-folder: /blog
    file:
      folder: /file
    image:
      size-s: thumbS