name: CICD

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ulvusuleymanov1/edadi .
      - name: Publish image to docker hub
        run: docker push ulvusuleymanov1/edadi:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: stop old container
        run: sudo docker stop edadi
      - name: Delete old container
        run: sudo docker rm -f edadi
      - name: Pull Image from docker hub
        run: sudo docker pull ulvusuleymanov1/edadi:latest
      - name: Run docker container
        run: sudo docker run -d -p 5000:5000 --name edadi ulvusuleymanov1/edadi