name: CICD

on:
  push:
    branches: [prod]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        env:
          SPRING_DATASOURCE_URL: ${{secrets.POSTGRES_URL}}
          SPRING_DATASOURCE_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          SPRING_DATASOURCE_PASSWORD: ${{secrets.POSt mTGRES_PASSWORD}}
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ulvusuleymanov1/edadi .
      - name: Publish image to docker hub
        run: docker push ulvusuleymanov1/edadi:latest
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull ulvusuleymanov1/edadi:latest
      - name: Delete old container
        run: sudo docker rm -f edadi
      - name: Run docker container
        run: sudo docker run -d -p 5000:5000 --name edadi -e POSTGRES_URL=${{secrets.POSTGRES_URL}} -e POSTGRES_USERNAME=${{secrets.POSTGRES_USERNAME}} -e POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} ulvusuleymanov1/edadi